project:
  type: book

book:
  title: "Effects of Glossolalia"
  author: "Jack B. Huber, Ph.D."
  date: "11/16/2022"
  chapters:
    - index.qmd
    - background.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt

editor: visual

