# VARIABLE LABELS
library(Hmisc)
var.labels <- c(
  Q7 = "My pastor/leader explicitly claiming to speak on God's behalf",
  Q10 = "Being asked to give up personal, vocational, and/or educational goals by a pastor or group leader",
  Q11 = "Seeing that anyone who disagreed with my church/pastor was consequently portrayed as evil",
  Q16 = "My church community abandoning me in a difficult time",
  Q17 = "Being treated as “less than” because of my sexual orientation",
  Q18 = "Discouragement of critical thinking by my church or pastor",
  Q19 = "Behavior being excessively monitored by my pastor or group members",
  Q20 = "Seeing specific members being pressured to give money despite well-known personal financial hardship",
  Q21 = "Being taught that I would be risking Hell if I left my particular church/group",
  Q22 = "Being expected to follow my pastor/leader’s personal rules/advice around dating, marriage, and sex",
  Q23 = "Prayer replacing needed medical interventions",
  Q24 = "Being expected to consult my pastor/leader before making non-religious decisions",
  Q25 = "Feeling unable to raise questions and issues",
  Q26 = "Being pressured to forgive an abuser while the abuse was ongoing",
  Q27 = "Being denied opportunities to serve/volunteer because of my gender",
  Q28 = "Seeing the leadership or group protecting abusive individuals",
  Q29 = "Feeling special when in my pastor/leader’s good graces; feeling ignored when I wasn’t",
  Q30 = "Being deterred from seeking mental health treatment, counseling and/or medication",
  Q31 = "Being shunned or ignored by my pastor or church/group",
  Q32 = "Feeling unable to express unhappiness",
  Q34 = "Seeing Scripture used to justify physical punishment or other types of severe discipline",
  Q35 = "Being explicitly taught to distrust my emotions",
  Q36 = "Mental or physical problems being interpreted as spiritual/moral weakness",
  Q37 = "Being made to feel less spiritually advanced/mature than my pastor/leadership",
  Q38 = "Having unrealistic demands placed on my moral or religious behavior",
  Q39 = "Being made to feel shame over naturally occurring sexual desires (not actions)",
  Q40 = "Threatening Divine punishment to keep group members in line",
  Q41 = "Being denied opportunities to serve because of my sexual orientation",
  Q42 = "Seeing others shamed or shunned by the pastor/leader or group",
  Q43 = "Being shamed by my pastor or the group for poor spiritual/moral performance",
  Q44 = "Love or acceptance only being offered if spiritual or moral performance was high",
  Q45 = "Vivid descriptions of Hell, Satan, or demons being taught to young children that are developmentally inappropriate and/or anxiety-provoking",
  Q46 = "Being treated as “less than” because of my skin color",
  Q47 = "Medical care being postponed or not given at all for religious reasons",
  Q49 = "The leadership or group not only protecting but elevating abusive individuals",
  Q50 = "Being treated as “less than” because of my gender",
  Q51 = "Experiencing extreme pressure to take on a role of pastor, missionary, or other spiritual leader",
  Q52 = "Being blamed for harm that I suffered, rather than blaming those who harmed me",
  Q53 = "Seeing Scripture used to justify abusive parent-child behavior",
  Q54 = "Being explicitly taught to distrust my intuitions",
  Q55 = "Hearing cultural references in sermons that were not commonly known to members of my racial or ethnic subculture",
  Q56 = "Being made to feel like I was crazy or weird for having doubts or questions",
  Q57 = "Developing mental or physical ailments as a result of stress from conforming to the group/leader’s expectation",
  Q58 = "Terror or horror being used to motivate religious decisions",
  Q59 = "Seeing the pastor or group blame the victim of abuse for the abuse itself",
  Q60 = "Being encouraged to remain in an abusive marriage by religious leaders",
  Q61 = "Vivid descriptions of the end of the world being taught to young children that are developmentally inappropriate and/or anxiety-provoking",
  Q62 = "Seeing Scripture used to justify physical violence",
  Q63 = "Being shamed by my pastor or the group for raising questions or concerns",
  Q64 = "Witnessing women being pressured to stay in unfaithful or abusive marriages",
  Q65 = "Being “cut off” or shunned by more religious family members",
  Q66 = "Seeing others treated as “less than” because of their sexual orientation",
  
  # VARIABLE LABELS: Items for Internal States Subscale
  Q68 = "Anxiety attacks triggered by religious stimuli",
  Q69 = "A lack of spiritual direction or purpose",
  Q70 = "Feeling betrayed by God",
  Q71 = "Personally avoiding religious activities or settings to reduce distressing feelings",
  Q72 = "Feeling as if God harmed me directly",
  Q73 = "Self-hatred or self-loathing",
  Q74 = "Sadness over the loss of my faith/religious community",
  Q76 = "Feeling that I wasted years of my life in a particular church or set of beliefs",
  Q77 = "Anger upon reflecting on negative religious experiences",
  Q78 = "A lack of self-worth",
  Q79 = "Distrust of God",
  Q80 = "Feeling isolated",
  Q81 = "Nightmares about my negative religious experiences",
  Q82 = "Having trouble navigating life outside my church/community")

library(labelled)
all <- labelled::set_variable_labels(all, .labels = var.labels)

library(expss)
# data(allitems)
data(shas)
shas = apply_labels(shas,
                    
                    # allitems = apply_labels(allitems,
                    
                    # Progressive podcasts
                    Q5 = "Weekly count progressive Christian podcast episodes",
                    
                    # VARIABLE LABELS: Items for External Events Subscale
                    Q7 = "My pastor/leader explicitly claiming to speak on God's behalf",
                    Q10 = "Being asked to give up personal, vocational, and/or educational goals by a pastor or group leader",
                    Q11 = "Seeing that anyone who disagreed with my church/pastor was consequently portrayed as evil",
                    Q16 = "My church community abandoning me in a difficult time",
                    Q17 = "Being treated as “less than” because of my sexual orientation",
                    Q18 = "Discouragement of critical thinking by my church or pastor",
                    Q19 = "Behavior being excessively monitored by my pastor or group members",
                    Q20 = "Seeing specific members being pressured to give money despite well-known personal financial hardship",
                    Q21 = "Being taught that I would be risking Hell if I left my particular church/group",
                    Q22 = "Being expected to follow my pastor/leader’s personal rules/advice around dating, marriage, and sex",
                    Q23 = "Prayer replacing needed medical interventions",
                    Q24 = "Being expected to consult my pastor/leader before making non-religious decisions",
                    Q25 = "Feeling unable to raise questions and issues",
                    Q26 = "Being pressured to forgive an abuser while the abuse was ongoing",
                    Q27 = "Being denied opportunities to serve/volunteer because of my gender",
                    Q28 = "Seeing the leadership or group protecting abusive individuals",
                    Q29 = "Feeling special when in my pastor/leader’s good graces; feeling ignored when I wasn’t",
                    Q30 = "Being deterred from seeking mental health treatment, counseling and/or medication",
                    Q31 = "Being shunned or ignored by my pastor or church/group",
                    Q32 = "Feeling unable to express unhappiness",
                    Q34 = "Seeing Scripture used to justify physical punishment or other types of severe discipline",
                    Q35 = "Being explicitly taught to distrust my emotions",
                    Q36 = "Mental or physical problems being interpreted as spiritual/moral weakness",
                    Q37 = "Being made to feel less spiritually advanced/mature than my pastor/leadership",
                    Q38 = "Having unrealistic demands placed on my moral or religious behavior",
                    Q39 = "Being made to feel shame over naturally occurring sexual desires (not actions)",
                    Q40 = "Threatening Divine punishment to keep group members in line",
                    Q41 = "Being denied opportunities to serve because of my sexual orientation",
                    Q42 = "Seeing others shamed or shunned by the pastor/leader or group",
                    Q43 = "Being shamed by my pastor or the group for poor spiritual/moral performance",
                    Q44 = "Love or acceptance only being offered if spiritual or moral performance was high",
                    Q45 = "Vivid descriptions of Hell, Satan, or demons being taught to young children that are developmentally inappropriate and/or anxiety-provoking",
                    Q46 = "Being treated as “less than” because of my skin color",
                    Q47 = "Medical care being postponed or not given at all for religious reasons",
                    Q49 = "The leadership or group not only protecting but elevating abusive individuals",
                    Q50 = "Being treated as “less than” because of my gender",
                    Q51 = "Experiencing extreme pressure to take on a role of pastor, missionary, or other spiritual leader",
                    Q52 = "Being blamed for harm that I suffered, rather than blaming those who harmed me",
                    Q53 = "Seeing Scripture used to justify abusive parent-child behavior",
                    Q54 = "Being explicitly taught to distrust my intuitions",
                    Q55 = "Hearing cultural references in sermons that were not commonly known to members of my racial or ethnic subculture",
                    Q56 = "Being made to feel like I was crazy or weird for having doubts or questions",
                    Q57 = "Developing mental or physical ailments as a result of stress from conforming to the group/leader’s expectation",
                    Q58 = "Terror or horror being used to motivate religious decisions",
                    Q59 = "Seeing the pastor or group blame the victim of abuse for the abuse itself",
                    Q60 = "Being encouraged to remain in an abusive marriage by religious leaders",
                    Q61 = "Vivid descriptions of the end of the world being taught to young children that are developmentally inappropriate and/or anxiety-provoking",
                    Q62 = "Seeing Scripture used to justify physical violence",
                    Q63 = "Being shamed by my pastor or the group for raising questions or concerns",
                    Q64 = "Witnessing women being pressured to stay in unfaithful or abusive marriages",
                    Q65 = "Being “cut off” or shunned by more religious family members",
                    Q66 = "Seeing others treated as “less than” because of their sexual orientation",
                    
                    # VARIABLE LABELS: Items for Internal States Subscale
                    Q68 = "Anxiety attacks triggered by religious stimuli",
                    Q69 = "A lack of spiritual direction or purpose",
                    Q70 = "Feeling betrayed by God",
                    Q71 = "Personally avoiding religious activities or settings to reduce distressing feelings",
                    Q72 = "Feeling as if God harmed me directly",
                    Q73 = "Self-hatred or self-loathing",
                    Q74 = "Sadness over the loss of my faith/religious community",
                    Q76 = "Feeling that I wasted years of my life in a particular church or set of beliefs",
                    Q77 = "Anger upon reflecting on negative religious experiences",
                    Q78 = "A lack of self-worth",
                    Q79 = "Distrust of God",
                    Q80 = "Feeling isolated",
                    Q81 = "Nightmares about my negative religious experiences",
                    Q82 = "Having trouble navigating life outside my church/community",
                    
                    # VALUE LABELS: Items for External Events Subscale
                    Q7  = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q10 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q11 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q16 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q17 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q18 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q19 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q20 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q21 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q22 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q23 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q24 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q25 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q26 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q27 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q28 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q29 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q30 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q31 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q32 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q34 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q35 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q36 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q37 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q38 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q39 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q40 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q41 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q42 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q43 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q44 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q45 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q46 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q47 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q49 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q50 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q51 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q52 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q53 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q54 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q55 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q56 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q57 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q58 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q59 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q60 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q61 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q62 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q63 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q64 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q65 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q66 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    
                    # VALUE LABELS for Internal States Subscale
                    Q68 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q69 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q70 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q71 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q72 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q73 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q74 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q76 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q77 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q78 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q80 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q81 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    Q82 = c("Never"=1,"Once or twice"=2,"Sometimes"=3,"Often"=4,"All the time"=5),
                    
                    # VARIABLE LABELS for Demographics
                    Q84 = "Age",
                    Q85 = "Gender",
                    Q86 = "Sexual orientation",
                    Q87 = "Race",
                    Q88 = "Raised in Christian home",
                    Q89 = "Denomination/group of most negative experience",
                    Q90 = "Racial makeup of denomination/group of most negative experience",
                    Q91 = "Race of leadership of denomination/group of most negative experience",
                    Q92 = "Gender of leadership of denomination/group of most negative experience",
                    Q95 = "Involvement in denomination/group of most negative experience",
                    Q93 = "Current religious identification",
                    
                    # VALUE LABELS for Demographics
                    Q85 = c("Cisgender Male"=1,"Cisgender Female"=2,"Transgender Male"=3,"Transgender Female"=4,"Other"=5,"Prefer not to say"=6),
                    Q86 = c("Straight"=1,"Gay/Lesbian"=2,"Bisexual"=3,"Asexual"=4,"Queer"=5,"Don't Know"=6),
                    Q87 = c("Ethnically of Hispanic/Latino origin"=1,"Black/African American"=2,"White/European American"=3,"Asian"=4,"American Indian/Alaska Native"=5,"Native Hawaiian/Pacific Islander"=6,"Other"=7),
                    Q88 = c("Yes"=1,"No"=2),
                    Q89 = c("Catholic"=1,"Charismatic/Pentecostal"=2,"Baptist"=3,"Mainline (Methodist, Lutheran, Episcopal/Anglican, Presbyterian, United Church of Christ, etc.)"=4,"Non-denominational"=5,"Orthodox Christian (Greek, Russian, Ethiopian, etc.)"=6,"Mormon"=7,"Christian church other than the above"=8,"Evangelistic/Missions organization (Billy Graham Assoc., YWAM, Fellowship of Christian Athletes, Teen Missions, Africa Inland Mission, Wycliff Bible Translators, Youth for Christ, etc.)"=9,"College Christian organization (Cru/Campus Crusade for Christ, InterVarsity, Navigators, etc.)"=10,"Christian Youth Organization (YoungLife, Awana, Teen Challenge, etc.)"=11,"Christian Media Company (Publisher, Record Label, Focus on the Family, etc.)"=12,"Christian school or university"=13,"Christian political/activist group"=14,"Christian aid/social services group (World Vision, Samaritan's Purse, Catholic Relief Services, etc.)"=15,"Local Bible study or small group"=16,"Christian group other than the above"=17),
                    Q90 = c("Predominantly white"=1,"Mixed race"=2,"Predominantly people of color"=3),
                    Q91 = c("Predominantly white"=1,"Mixed race"=2,"Predominantly people of color"=3),
                    Q92 = c("All male"=1,"Mostly male"=2,"Mixed gender"=3,"Mostly female"=4,"All female"=5),
                    Q95 = c("Strongly disagree"=1,"2"=2,"3"=3,"4"=4,"5"=5,"6"=6,"Strongly agree"=7),
                    Q93 = c("Protestant"=1,"Catholic"=2,"Mormon"=3,"Orthodox Christian"=4,"Other religious tradition (Jewish, Muslim, Buddhist, etc.)"=5,"Atheist"=6,"Agnostic"=7,"Nothing in particular"=8),
                    
                    # VARIABLE LABELS for If current = Protestant/Catholic/Mormon/Orthodox Christian
                    Q97 = "Current theological self-perception",
                    Q98 = "Current feelings about the Bible",
                    
                    # VALUE LABELS for If current = Protestant/Catholic/Mormon/Orthodox Christian
                    Q97 = c("Very Conservative"=1,"2"=2,"3"=3,"In the Middle"=4,"5"=5,"6"=6,"Very Liberal"=7),
                    Q98 = c("The Bible is the actual word of God and is to be taken literally, word for word"=1,"The Bible is the inspired word of God but not everything should be taken literally, word for word"=2,"The Bible is an ancient book of fables, legends, history and moral precepts recorded by man"=3)